[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }

leptos = { version = "0.7.7", features = ["csr"] }
leptos_router = "0.7.8"
leptos_meta = "0.7.8"

reqwest = "0.12.12"
anyhow = "1.0.97"
serde_json = "1.0.140"
console_error_panic_hook = "0.1.7"
url = "2.5.4"
