[build]
# Enable a small amount of optimization in debug mode
rustflags = ["-C", "opt-level=0"]
# Clean cargo output which can help with rebuilds
clean-dist = true
release = false

[watch]
ignore = ["dist"]
