[build]
# Enable a small amount of optimization in debug mode
rustflags = ["-C", "opt-level=1"]
# Clean cargo output which can help with rebuilds
clean-dist = true
release = false

[watch]
# Ignore output files and target directory to prevent unnecessary rebuilds
ignore = ["dist"]

[serve]
addresses = ["127.0.0.1"]  # The address to serve on.
port = 8080                # The port to serve on.