services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/webidler.gregoirenaisse.be/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/webidler.gregoirenaisse.be/privkey.pem:/etc/nginx/ssl/privkey.pem
    ports:
      - 80:80
      - 443:443
    restart: always

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    