services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    restart: always

  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    