mod account;
mod game;
mod leaderboard;
mod main_menu;
pub mod privacy;
mod reset_password;
mod signup;
pub mod terms;
mod town;
mod user_dashboard;
mod view_character;

pub use account::AccountSettingsPage;
pub use game::GamePage;
pub use leaderboard::LeaderboardPage;
pub use main_menu::MainMenuPage;
pub use reset_password::ResetPasswordPage;
pub use signup::SignUpPage;
pub use town::TownPage;
pub use user_dashboard::UserDashboardPage;
pub use view_character::ViewCharacterPage;
