use aho_corasick::AhoCorasick;
use itertools::Itertools;
use regex::Regex;
use std::{collections::HashMap, fs};
use unicode_normalization::UnicodeNormalization;

pub struct ProfanitiesChecker {
    // profanity_list: HashSet<String>,
    strong_matcher: AhoCorasick,
    weak_matcher: Regex,
    leet_map: HashMap<char, char>,
}

impl ProfanitiesChecker {
    pub fn load_from_file(
        strong_path: &'static str,
        weak_path: &'static str,
    ) -> anyhow::Result<Self> {
        let strong_content = fs::read_to_string(strong_path)?;
        let weak_content = fs::read_to_string(weak_path)?;

        Ok(Self {
            strong_matcher: AhoCorasick::builder()
                // .ascii_case_insensitive(true)
                .build(
                    strong_content
                        .lines()
                        .map(str::trim)
                        .filter(|line| !line.is_empty() && !line.starts_with('#'))
                        .map(|line| line.to_lowercase()),
                )?,
            weak_matcher: Regex::new(&format!(
                r"\b({})\b",
                weak_content
                    .lines()
                    .map(str::trim)
                    .filter(|line| !line.is_empty() && !line.starts_with('#'))
                    .map(|line| line.to_lowercase())
                    .join("|")
            ))?,
            leet_map: HashMap::from([
                ('0', 'o'),
                ('1', 'i'),
                ('3', 'e'),
                ('4', 'a'),
                ('5', 's'),
                ('7', 't'),
                ('@', 'a'),
                ('$', 's'),
                ('!', 'i'),
                ('+', 't'),
                // Squared letters (🅰-🆉)
                ('🅰', 'a'),
                ('🅱', 'b'),
                ('🅲', 'c'),
                ('🅳', 'd'),
                ('🅴', 'e'),
                ('🅵', 'f'),
                ('🅶', 'g'),
                ('🅷', 'h'),
                ('🅸', 'i'),
                ('🅹', 'j'),
                ('🅺', 'k'),
                ('🅻', 'l'),
                ('🅼', 'm'),
                ('🅽', 'n'),
                ('🅾', 'o'),
                ('🅿', 'p'),
                ('🆀', 'q'),
                ('🆁', 'r'),
                ('🆂', 's'),
                ('🆃', 't'),
                ('🆄', 'u'),
                ('🆅', 'v'),
                ('🆆', 'w'),
                ('🆇', 'x'),
                ('🆈', 'y'),
                ('🆉', 'z'),
                // Circled letters (Ⓐ-Ⓩ)
                ('Ⓐ', 'a'),
                ('Ⓑ', 'b'),
                ('Ⓒ', 'c'),
                ('Ⓓ', 'd'),
                ('Ⓔ', 'e'),
                ('Ⓕ', 'f'),
                ('Ⓖ', 'g'),
                ('Ⓗ', 'h'),
                ('Ⓘ', 'i'),
                ('Ⓙ', 'j'),
                ('Ⓚ', 'k'),
                ('Ⓛ', 'l'),
                ('Ⓜ', 'm'),
                ('Ⓝ', 'n'),
                ('Ⓞ', 'o'),
                ('Ⓟ', 'p'),
                ('Ⓠ', 'q'),
                ('Ⓡ', 'r'),
                ('Ⓢ', 's'),
                ('Ⓣ', 't'),
                ('Ⓤ', 'u'),
                ('Ⓥ', 'v'),
                ('Ⓦ', 'w'),
                ('Ⓧ', 'x'),
                ('Ⓨ', 'y'),
                ('Ⓩ', 'z'),
                // Circled lowercase letters (ⓐ-ⓩ)
                ('ⓐ', 'a'),
                ('ⓑ', 'b'),
                ('ⓒ', 'c'),
                ('ⓓ', 'd'),
                ('ⓔ', 'e'),
                ('ⓕ', 'f'),
                ('ⓖ', 'g'),
                ('ⓗ', 'h'),
                ('ⓘ', 'i'),
                ('ⓙ', 'j'),
                ('ⓚ', 'k'),
                ('ⓛ', 'l'),
                ('ⓜ', 'm'),
                ('ⓝ', 'n'),
                ('ⓞ', 'o'),
                ('ⓟ', 'p'),
                ('ⓠ', 'q'),
                ('ⓡ', 'r'),
                ('ⓢ', 's'),
                ('ⓣ', 't'),
                ('ⓤ', 'u'),
                ('ⓥ', 'v'),
                ('ⓦ', 'w'),
                ('ⓧ', 'x'),
                ('ⓨ', 'y'),
                ('ⓩ', 'z'),
                // Mathematical alphanumeric symbols - Bold
                ('𝐀', 'a'),
                ('𝐁', 'b'),
                ('𝐂', 'c'),
                ('𝐃', 'd'),
                ('𝐄', 'e'),
                ('𝐅', 'f'),
                ('𝐆', 'g'),
                ('𝐇', 'h'),
                ('𝐈', 'i'),
                ('𝐉', 'j'),
                ('𝐊', 'k'),
                ('𝐋', 'l'),
                ('𝐌', 'm'),
                ('𝐍', 'n'),
                ('𝐎', 'o'),
                ('𝐏', 'p'),
                ('𝐐', 'q'),
                ('𝐑', 'r'),
                ('𝐒', 's'),
                ('𝐓', 't'),
                ('𝐔', 'u'),
                ('𝐕', 'v'),
                ('𝐖', 'w'),
                ('𝐗', 'x'),
                ('𝐘', 'y'),
                ('𝐙', 'z'),
                // Mathematical alphanumeric symbols - Bold lowercase
                ('𝐚', 'a'),
                ('𝐛', 'b'),
                ('𝐜', 'c'),
                ('𝐝', 'd'),
                ('𝐞', 'e'),
                ('𝐟', 'f'),
                ('𝐠', 'g'),
                ('𝐡', 'h'),
                ('𝐢', 'i'),
                ('𝐣', 'j'),
                ('𝐤', 'k'),
                ('𝐥', 'l'),
                ('𝐦', 'm'),
                ('𝐧', 'n'),
                ('𝐨', 'o'),
                ('𝐩', 'p'),
                ('𝐪', 'q'),
                ('𝐫', 'r'),
                ('𝐬', 's'),
                ('𝐭', 't'),
                ('𝐮', 'u'),
                ('𝐯', 'v'),
                ('𝐰', 'w'),
                ('𝐱', 'x'),
                ('𝐲', 'y'),
                ('𝐳', 'z'),
                // Mathematical alphanumeric symbols - Italic
                ('𝘈', 'a'),
                ('𝘉', 'b'),
                ('𝘊', 'c'),
                ('𝘋', 'd'),
                ('𝘌', 'e'),
                ('𝘍', 'f'),
                ('𝘎', 'g'),
                ('𝘏', 'h'),
                ('𝘐', 'i'),
                ('𝘑', 'j'),
                ('𝘒', 'k'),
                ('𝘓', 'l'),
                ('𝘔', 'm'),
                ('𝘕', 'n'),
                ('𝘖', 'o'),
                ('𝘗', 'p'),
                ('𝘘', 'q'),
                ('𝘙', 'r'),
                ('𝘚', 's'),
                ('𝘛', 't'),
                ('𝘜', 'u'),
                ('𝘝', 'v'),
                ('𝘞', 'w'),
                ('𝘟', 'x'),
                ('𝘠', 'y'),
                ('𝘡', 'z'),
                // Mathematical alphanumeric symbols - Italic lowercase
                ('𝘢', 'a'),
                ('𝘣', 'b'),
                ('𝘤', 'c'),
                ('𝘥', 'd'),
                ('𝘦', 'e'),
                ('𝘧', 'f'),
                ('𝘨', 'g'),
                ('𝘩', 'h'),
                ('𝘪', 'i'),
                ('𝘫', 'j'),
                ('𝘬', 'k'),
                ('𝘭', 'l'),
                ('𝘮', 'm'),
                ('𝘯', 'n'),
                ('𝘰', 'o'),
                ('𝘱', 'p'),
                ('𝘲', 'q'),
                ('𝘳', 'r'),
                ('𝘴', 's'),
                ('𝘵', 't'),
                ('𝘶', 'u'),
                ('𝘷', 'v'),
                ('𝘸', 'w'),
                ('𝘹', 'x'),
                ('𝘺', 'y'),
                ('𝘻', 'z'),
                // Mathematical alphanumeric symbols - Bold Italic
                ('𝙰', 'a'),
                ('𝙱', 'b'),
                ('𝙲', 'c'),
                ('𝙳', 'd'),
                ('𝙴', 'e'),
                ('𝙵', 'f'),
                ('𝙶', 'g'),
                ('𝙷', 'h'),
                ('𝙸', 'i'),
                ('𝙹', 'j'),
                ('𝙺', 'k'),
                ('𝙻', 'l'),
                ('𝙼', 'm'),
                ('𝙽', 'n'),
                ('𝙾', 'o'),
                ('𝙿', 'p'),
                ('𝚀', 'q'),
                ('𝚁', 'r'),
                ('𝚂', 's'),
                ('𝚃', 't'),
                ('𝚄', 'u'),
                ('𝚅', 'v'),
                ('𝚆', 'w'),
                ('𝚇', 'x'),
                ('𝚈', 'y'),
                ('𝚉', 'z'),
                // Mathematical alphanumeric symbols - Bold Italic lowercase
                ('𝙖', 'a'),
                ('𝙗', 'b'),
                ('𝙘', 'c'),
                ('𝙙', 'd'),
                ('𝙚', 'e'),
                ('𝙛', 'f'),
                ('𝙜', 'g'),
                ('𝙝', 'h'),
                ('𝙞', 'i'),
                ('𝙟', 'j'),
                ('𝙠', 'k'),
                ('𝙡', 'l'),
                ('𝙢', 'm'),
                ('𝙣', 'n'),
                ('𝙤', 'o'),
                ('𝙥', 'p'),
                ('𝙦', 'q'),
                ('𝙧', 'r'),
                ('𝙨', 's'),
                ('𝙩', 't'),
                ('𝙪', 'u'),
                ('𝙫', 'v'),
                ('𝙬', 'w'),
                ('𝙭', 'x'),
                ('𝙮', 'y'),
                ('𝙯', 'z'),
                // Mathematical alphanumeric symbols - Double-struck
                ('𝔸', 'a'),
                ('𝔹', 'b'),
                ('ℂ', 'c'),
                ('𝔻', 'd'),
                ('𝔼', 'e'),
                ('𝔽', 'f'),
                ('𝔾', 'g'),
                ('ℍ', 'h'),
                ('𝕀', 'i'),
                ('𝕁', 'j'),
                ('𝕂', 'k'),
                ('𝕃', 'l'),
                ('𝕄', 'm'),
                ('ℕ', 'n'),
                ('𝕆', 'o'),
                ('ℙ', 'p'),
                ('ℚ', 'q'),
                ('ℝ', 'r'),
                ('𝕊', 's'),
                ('𝕋', 't'),
                ('𝕌', 'u'),
                ('𝕍', 'v'),
                ('𝕎', 'w'),
                ('𝕏', 'x'),
                ('𝕐', 'y'),
                ('ℤ', 'z'),
                // Mathematical alphanumeric symbols - Double-struck lowercase
                ('𝕒', 'a'),
                ('𝕓', 'b'),
                ('𝕔', 'c'),
                ('𝕕', 'd'),
                ('𝕖', 'e'),
                ('𝕗', 'f'),
                ('𝕘', 'g'),
                ('𝕙', 'h'),
                ('𝕚', 'i'),
                ('𝕛', 'j'),
                ('𝕜', 'k'),
                ('𝕝', 'l'),
                ('𝕞', 'm'),
                ('𝕟', 'n'),
                ('𝕠', 'o'),
                ('𝕡', 'p'),
                ('𝕢', 'q'),
                ('𝕣', 'r'),
                ('𝕤', 's'),
                ('𝕥', 't'),
                ('𝕦', 'u'),
                ('𝕧', 'v'),
                ('𝕨', 'w'),
                ('𝕩', 'x'),
                ('𝕪', 'y'),
                ('𝕫', 'z'),
                // Mathematical alphanumeric symbols - Fraktur (Gothic)
                ('𝔄', 'a'),
                ('𝔅', 'b'),
                ('ℭ', 'c'),
                ('𝔇', 'd'),
                ('𝔈', 'e'),
                ('𝔉', 'f'),
                ('𝔊', 'g'),
                ('ℌ', 'h'),
                ('ℑ', 'i'),
                ('𝔍', 'j'),
                ('𝔎', 'k'),
                ('𝔏', 'l'),
                ('𝔐', 'm'),
                ('𝔑', 'n'),
                ('𝔒', 'o'),
                ('𝔓', 'p'),
                ('𝔔', 'q'),
                ('ℜ', 'r'),
                ('𝔖', 's'),
                ('𝔗', 't'),
                ('𝔘', 'u'),
                ('𝔙', 'v'),
                ('𝔚', 'w'),
                ('𝔛', 'x'),
                ('𝔜', 'y'),
                ('ℨ', 'z'),
                // Mathematical alphanumeric symbols - Fraktur lowercase
                ('𝔞', 'a'),
                ('𝔟', 'b'),
                ('𝔠', 'c'),
                ('𝔡', 'd'),
                ('𝔢', 'e'),
                ('𝔣', 'f'),
                ('𝔤', 'g'),
                ('𝔥', 'h'),
                ('𝔦', 'i'),
                ('𝔧', 'j'),
                ('𝔨', 'k'),
                ('𝔩', 'l'),
                ('𝔪', 'm'),
                ('𝔫', 'n'),
                ('𝔬', 'o'),
                ('𝔭', 'p'),
                ('𝔮', 'q'),
                ('𝔯', 'r'),
                ('𝔰', 's'),
                ('𝔱', 't'),
                ('𝔲', 'u'),
                ('𝔳', 'v'),
                ('𝔴', 'w'),
                ('𝔵', 'x'),
                ('𝔶', 'y'),
                ('𝔷', 'z'),
                // Mathematical alphanumeric symbols - Script
                ('𝒜', 'a'),
                ('𝒷', 'b'),
                ('𝒸', 'c'),
                ('𝒹', 'd'),
                ('ℯ', 'e'),
                ('𝒻', 'f'),
                ('ℊ', 'g'),
                ('𝒽', 'h'),
                ('𝒾', 'i'),
                ('𝒿', 'j'),
                ('𝓀', 'k'),
                ('𝓁', 'l'),
                ('𝓂', 'm'),
                ('𝓃', 'n'),
                ('ℴ', 'o'),
                ('𝓅', 'p'),
                ('𝓆', 'q'),
                ('𝓇', 'r'),
                ('𝓈', 's'),
                ('𝓉', 't'),
                ('𝓊', 'u'),
                ('𝓋', 'v'),
                ('𝓌', 'w'),
                ('𝓍', 'x'),
                ('𝓎', 'y'),
                ('𝓏', 'z'),
                // Mathematical alphanumeric symbols - Bold Script
                ('𝓐', 'a'),
                ('𝓑', 'b'),
                ('𝓒', 'c'),
                ('𝓓', 'd'),
                ('𝓔', 'e'),
                ('𝓕', 'f'),
                ('𝓖', 'g'),
                ('𝓗', 'h'),
                ('𝓘', 'i'),
                ('𝓙', 'j'),
                ('𝓚', 'k'),
                ('𝓛', 'l'),
                ('𝓜', 'm'),
                ('𝓝', 'n'),
                ('𝓞', 'o'),
                ('𝓟', 'p'),
                ('𝓠', 'q'),
                ('𝓡', 'r'),
                ('𝓢', 's'),
                ('𝓣', 't'),
                ('𝓤', 'u'),
                ('𝓥', 'v'),
                ('𝓦', 'w'),
                ('𝓧', 'x'),
                ('𝓨', 'y'),
                ('𝓩', 'z'),
                // Mathematical alphanumeric symbols - Bold Script lowercase
                ('𝓪', 'a'),
                ('𝓫', 'b'),
                ('𝓬', 'c'),
                ('𝓭', 'd'),
                ('𝓮', 'e'),
                ('𝓯', 'f'),
                ('𝓰', 'g'),
                ('𝓱', 'h'),
                ('𝓲', 'i'),
                ('𝓳', 'j'),
                ('𝓴', 'k'),
                ('𝓵', 'l'),
                ('𝓶', 'm'),
                ('𝓷', 'n'),
                ('𝓸', 'o'),
                ('𝓹', 'p'),
                ('𝓺', 'q'),
                ('𝓻', 'r'),
                ('𝓼', 's'),
                ('𝓽', 't'),
                ('𝓾', 'u'),
                ('𝓿', 'v'),
                ('𝔀', 'w'),
                ('𝔁', 'x'),
                ('𝔂', 'y'),
                ('𝔃', 'z'),
                // Mathematical alphanumeric symbols - Monospace
                ('𝙰', 'a'),
                ('𝙱', 'b'),
                ('𝙲', 'c'),
                ('𝙳', 'd'),
                ('𝙴', 'e'),
                ('𝙵', 'f'),
                ('𝙶', 'g'),
                ('𝙷', 'h'),
                ('𝙸', 'i'),
                ('𝙹', 'j'),
                ('𝙺', 'k'),
                ('𝙻', 'l'),
                ('𝙼', 'm'),
                ('𝙽', 'n'),
                ('𝙾', 'o'),
                ('𝙿', 'p'),
                ('𝚀', 'q'),
                ('𝚁', 'r'),
                ('𝚂', 's'),
                ('𝚃', 't'),
                ('𝚄', 'u'),
                ('𝚅', 'v'),
                ('𝚆', 'w'),
                ('𝚇', 'x'),
                ('𝚈', 'y'),
                ('𝚉', 'z'),
                // Mathematical alphanumeric symbols - Monospace lowercase
                ('𝚊', 'a'),
                ('𝚋', 'b'),
                ('𝚌', 'c'),
                ('𝚍', 'd'),
                ('𝚎', 'e'),
                ('𝚏', 'f'),
                ('𝚐', 'g'),
                ('𝚑', 'h'),
                ('𝚒', 'i'),
                ('𝚓', 'j'),
                ('𝚔', 'k'),
                ('𝚕', 'l'),
                ('𝚖', 'm'),
                ('𝚗', 'n'),
                ('𝚘', 'o'),
                ('𝚙', 'p'),
                ('𝚚', 'q'),
                ('𝚛', 'r'),
                ('𝚜', 's'),
                ('𝚝', 't'),
                ('𝚞', 'u'),
                ('𝚟', 'v'),
                ('𝚠', 'w'),
                ('𝚡', 'x'),
                ('𝚢', 'y'),
                ('𝚣', 'z'),
            ]),
        })
    }

    pub fn find_profanity(&self, content: &str) -> Option<String> {
        let weak_normalized = self.weak_normalize(content);
        let strong_normalized = self.strong_normalize(&weak_normalized);

        if let Some(m) = self.strong_matcher.find(&strong_normalized) {
            return Some(strong_normalized[m.start()..m.end()].to_string());
        }

        if let Some(m) = self.weak_matcher.find(&weak_normalized) {
            return Some(weak_normalized[m.start()..m.end()].to_string());
        }

        None
    }

    pub fn weak_normalize(&self, content: &str) -> String {
        collapse_repeated_chars(
            content.nfkc().flat_map(|c| c.to_lowercase()).map(|c| {
                if let Some(repl) = self.leet_map.get(&c) {
                    *repl
                } else {
                    c
                }
            }),
            content.len(),
        )
    }

    pub fn strong_normalize(&self, content: &str) -> String {
        content.chars().filter(|c| c.is_alphanumeric()).collect()
    }
}

fn collapse_repeated_chars(input: impl Iterator<Item = char>, capacity: usize) -> String {
    let mut result = String::with_capacity(capacity);

    let mut prev: Option<char> = None;
    let mut count = 0;

    for c in input {
        match prev {
            Some(p) if p == c => {
                count += 1;
                if count <= 2 {
                    result.push(c);
                }
            }
            _ => {
                prev = Some(c);
                count = 1;
                result.push(c);
            }
        }
    }

    result
}
