name: FrontendItchIO

on:
  push:
    branches: ["main"]
    paths:
      [
        "frontend/**",
        "shared/**",
        "assets/**",
        ".github/workflows/itchio-frontend-deploy.yml",
      ]

jobs:
  Frontend-Build-and-deploy-to-ItchIO:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # repo checkout

      # Install Rust Nightly Toolchain, with Clippy & Rustfmt
      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Download and install Trunk binary
        working-directory: ./frontend
        run: wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler

      - name: Build with Trunk
        working-directory: ./frontend
        env:
          BACKEND_HTTP_URL: "https://webidler.gregoirenaisse.be"
          BACKEND_WS_URL: "wss://webidler.gregoirenaisse.be"
          BACKEND_CHAT_WS_URL: "wss://webidler.gregoirenaisse.be/chatws"
        run: |
          ./trunk build --release --config "./Trunk-release.toml" --public-url "./"

      - name: Upload to itch.io
        run: ./butler push ./frontend/dist gregouar/grind-to-rust:web
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
